// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvxqzz2yAD-ZT2DlflF83sA-VlvGCKKX4',
    appId: '1:953435328785:web:33e073af1075573a14bcb0',
    messagingSenderId: '953435328785',
    projectId: 'memo-179ad',
    authDomain: 'memo-179ad.firebaseapp.com',
    storageBucket: 'memo-179ad.firebasestorage.app',
    measurementId: 'G-53WX50NZ4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrn6SI9UVKh0sVmAFUjWlbLkiG9nyBKsY',
    appId: '1:953435328785:android:a64006905c8cea0014bcb0',
    messagingSenderId: '953435328785',
    projectId: 'memo-179ad',
    storageBucket: 'memo-179ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFptyAsMbim_wbQYUCdf35DCjt57t8PK8',
    appId: '1:953435328785:ios:ab6ecb829ac3806d14bcb0',
    messagingSenderId: '953435328785',
    projectId: 'memo-179ad',
    storageBucket: 'memo-179ad.firebasestorage.app',
    iosBundleId: 'com.example.004Notice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFptyAsMbim_wbQYUCdf35DCjt57t8PK8',
    appId: '1:953435328785:ios:ab6ecb829ac3806d14bcb0',
    messagingSenderId: '953435328785',
    projectId: 'memo-179ad',
    storageBucket: 'memo-179ad.firebasestorage.app',
    iosBundleId: 'com.example.004Notice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvxqzz2yAD-ZT2DlflF83sA-VlvGCKKX4',
    appId: '1:953435328785:web:9ca1b4110f4119c414bcb0',
    messagingSenderId: '953435328785',
    projectId: 'memo-179ad',
    authDomain: 'memo-179ad.firebaseapp.com',
    storageBucket: 'memo-179ad.firebasestorage.app',
    measurementId: 'G-TJLM5D39BZ',
  );
}
